application: w
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /admin/?.*
  script: admin.py
  login: admin

- url: /.*
  script: w.py

